//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoV.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CoV.Common.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        public static string ConfirmLogout {
            get {
                return ResourceManager.GetString("ConfirmLogout", resourceCulture);
            }
        }
        
        public static string ConfirmMoveUser {
            get {
                return ResourceManager.GetString("ConfirmMoveUser", resourceCulture);
            }
        }
        
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        public static string EmailValidator {
            get {
                return ResourceManager.GetString("EmailValidator", resourceCulture);
            }
        }
        
        public static string ExpiredToken {
            get {
                return ResourceManager.GetString("ExpiredToken", resourceCulture);
            }
        }
        
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        public static string GreaterThanOrEqualValidator {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualValidator", resourceCulture);
            }
        }
        
        public static string GreaterThanValidator {
            get {
                return ResourceManager.GetString("GreaterThanValidator", resourceCulture);
            }
        }
        
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        public static string InvalidImportFormat {
            get {
                return ResourceManager.GetString("InvalidImportFormat", resourceCulture);
            }
        }
        
        public static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        public static string InvalidSmartphone {
            get {
                return ResourceManager.GetString("InvalidSmartphone", resourceCulture);
            }
        }
        
        public static string InvilidExtension {
            get {
                return ResourceManager.GetString("InvilidExtension", resourceCulture);
            }
        }
        
        public static string LengthNotGreaterThan {
            get {
                return ResourceManager.GetString("LengthNotGreaterThan", resourceCulture);
            }
        }
        
        public static string LengthNotLessThan {
            get {
                return ResourceManager.GetString("LengthNotLessThan", resourceCulture);
            }
        }
        
        public static string LengthValidator {
            get {
                return ResourceManager.GetString("LengthValidator", resourceCulture);
            }
        }
        
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        public static string LessThanOrEqualValidator {
            get {
                return ResourceManager.GetString("LessThanOrEqualValidator", resourceCulture);
            }
        }
        
        public static string LessThanValidator {
            get {
                return ResourceManager.GetString("LessThanValidator", resourceCulture);
            }
        }
        
        public static string MaximumLengthValidator {
            get {
                return ResourceManager.GetString("MaximumLengthValidator", resourceCulture);
            }
        }
        
        public static string MinimumLengthValidator {
            get {
                return ResourceManager.GetString("MinimumLengthValidator", resourceCulture);
            }
        }
        
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        public static string NonExistedToken {
            get {
                return ResourceManager.GetString("NonExistedToken", resourceCulture);
            }
        }
        
        public static string NotGreaterThan {
            get {
                return ResourceManager.GetString("NotGreaterThan", resourceCulture);
            }
        }
        
        public static string NotLessThan {
            get {
                return ResourceManager.GetString("NotLessThan", resourceCulture);
            }
        }
        
        public static string NotNullValidator {
            get {
                return ResourceManager.GetString("NotNullValidator", resourceCulture);
            }
        }
        
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        public static string RefreshTokenNotFound {
            get {
                return ResourceManager.GetString("RefreshTokenNotFound", resourceCulture);
            }
        }
        
        public static string RefreshTokenRevoked {
            get {
                return ResourceManager.GetString("RefreshTokenRevoked", resourceCulture);
            }
        }
        
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        public static string RequiredFile {
            get {
                return ResourceManager.GetString("RequiredFile", resourceCulture);
            }
        }
        
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        public static string UserLoginFailed {
            get {
                return ResourceManager.GetString("UserLoginFailed", resourceCulture);
            }
        }
        
        public static string LoginCustomerSingUpFailed {
            get {
                return ResourceManager.GetString("LoginCustomerSingUpFailed", resourceCulture);
            }
        }
        
        public static string CustomerSingUpFailed {
            get {
                return ResourceManager.GetString("CustomerSingUpFailed", resourceCulture);
            }
        }
        
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        public static string AnUnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        public static string GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("GreaterThanOrEqual", resourceCulture);
            }
        }
        
        public static string FindDataRequest {
            get {
                return ResourceManager.GetString("FindDataRequest", resourceCulture);
            }
        }
        
        public static string ChangePassFailed {
            get {
                return ResourceManager.GetString("ChangePassFailed", resourceCulture);
            }
        }
        
        public static string NullPassword {
            get {
                return ResourceManager.GetString("NullPassword", resourceCulture);
            }
        }
        
        public static string ConfiguePassword {
            get {
                return ResourceManager.GetString("ConfiguePassword", resourceCulture);
            }
        }
        
        public static string NullPasswordConfirm {
            get {
                return ResourceManager.GetString("NullPasswordConfirm", resourceCulture);
            }
        }
        
        public static string msgSync {
            get {
                return ResourceManager.GetString("msgSync", resourceCulture);
            }
        }
        
        public static string NullUserPass {
            get {
                return ResourceManager.GetString("NullUserPass", resourceCulture);
            }
        }
        
        public static string UserNameNotNull {
            get {
                return ResourceManager.GetString("UserNameNotNull", resourceCulture);
            }
        }
        
        public static string UserNameMaxLength {
            get {
                return ResourceManager.GetString("UserNameMaxLength", resourceCulture);
            }
        }
        
        public static string PassWorkNotNull {
            get {
                return ResourceManager.GetString("PassWorkNotNull", resourceCulture);
            }
        }
        
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        public static string PasswordMixLength {
            get {
                return ResourceManager.GetString("PasswordMixLength", resourceCulture);
            }
        }
        
        public static string errer404 {
            get {
                return ResourceManager.GetString("errer404", resourceCulture);
            }
        }
        
        public static string error401 {
            get {
                return ResourceManager.GetString("error401", resourceCulture);
            }
        }
        
        public static string error500 {
            get {
                return ResourceManager.GetString("error500", resourceCulture);
            }
        }
        
        public static string DateTimeMin {
            get {
                return ResourceManager.GetString("DateTimeMin", resourceCulture);
            }
        }
        
        public static string NotNullValue {
            get {
                return ResourceManager.GetString("NotNullValue", resourceCulture);
            }
        }
        
        public static string MaxWord {
            get {
                return ResourceManager.GetString("MaxWord", resourceCulture);
            }
        }
        
        public static string MinWord {
            get {
                return ResourceManager.GetString("MinWord", resourceCulture);
            }
        }
        
        public static string MaxlengthNumber {
            get {
                return ResourceManager.GetString("MaxlengthNumber", resourceCulture);
            }
        }
        
        public static string MinlengthNumber {
            get {
                return ResourceManager.GetString("MinlengthNumber", resourceCulture);
            }
        }
        
        public static string ProductdetailNull {
            get {
                return ResourceManager.GetString("ProductdetailNull", resourceCulture);
            }
        }
        
        public static string skuProductKey {
            get {
                return ResourceManager.GetString("skuProductKey", resourceCulture);
            }
        }
        
        public static string UserNameExist {
            get {
                return ResourceManager.GetString("UserNameExist", resourceCulture);
            }
        }
    }
}
